
    <!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 static/models/scene.gltf --root /models --types --no-prettier
Author: Petri Liuhto (https://sketchfab.com/petri.liuhto)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/jedi-star-fighter-0b641c2f2b854f1f9ae7f2a731e44dbd
Title: Jedi Star Fighter
-->




    <script lang="ts">
				
	
import type * as THREE from 'three'
	
  import type { Snippet } from 'svelte'
        import { T, type Props } from '@threlte/core'
        import { useGltf } from '@threlte/extras'
	

        let {
					fallback,
          error,
          children,
          ref = $bindable(),
          ...props
        }: Props<THREE.Group> &  {
          ref?: THREE.Group
          children?: Snippet<[{ ref: THREE.Group }]>
          fallback?: Snippet
          error?: Snippet<[{ error: Error }]>
        } = $props()

				

				

        type GLTFResult = {
    nodes: {
      main_jsf_mainMat_0: THREE.Mesh,main_jsf_mainMat_0_1: THREE.Mesh,aux_jsf_auxMat_0: THREE.Mesh,aux_jsf_auxMat_0_1: THREE.Mesh
      
    }
    materials: {
      jsf_mainMat: THREE.MeshStandardMaterial,jsf_auxMat: THREE.MeshStandardMaterial
    }
  }

        const gltf = useGltf<GLTFResult>('/modelsscene.gltf')

    
    </script>

		<T.Group bind:ref dispose={false} {...props}>
			{#await gltf}
        {@render fallback?.()}
			{:then gltf}
				<T.Group rotation={[-Math.PI / 2, 0, 0,]} scale={100} >
<T.Mesh geometry={gltf.nodes.main_jsf_mainMat_0.geometry} material={gltf.materials.jsf_mainMat} />
<T.Mesh geometry={gltf.nodes.main_jsf_mainMat_0_1.geometry} material={gltf.materials.jsf_mainMat} />

</T.Group>
<T.Group rotation={[-Math.PI / 2, 0, 0,]} scale={100} >
<T.Mesh geometry={gltf.nodes.aux_jsf_auxMat_0.geometry} material={gltf.materials.jsf_auxMat} />
<T.Mesh geometry={gltf.nodes.aux_jsf_auxMat_0_1.geometry} material={gltf.materials.jsf_auxMat} />

</T.Group>

			{:catch err}
        {@render error?.({ error: err })}
			{/await}

      {@render children?.({ ref })}
		</T.Group>
	