
    <!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 /app/static/models/threlte.glb --root /models/ --types --printwidth 120 --precision 2
-->




    <script lang="ts">
				
	
import type * as THREE from 'three'
	
  import type { Snippet } from 'svelte'
        import { T, type Props } from '@threlte/core'
        import { useGltf } from '@threlte/extras'
	

        let {
					fallback,
          error,
          children,
          ref = $bindable(),
          ...props
        }: Props<THREE.Group> &  {
          ref?: THREE.Group
          children?: Snippet<[{ ref: THREE.Group }]>
          fallback?: Snippet
          error?: Snippet<[{ error: Error }]>
        } = $props()

				

				

        type GLTFResult = {
    nodes: {
      Cube: THREE.Mesh
      
    }
    materials: {
      Material: THREE.MeshStandardMaterial
    }
  }

        const gltf = useGltf<GLTFResult>('/models/threlte.glb')

    
    </script>

		<T.Group bind:ref dispose={false} {...props}>
			{#await gltf}
        {@render fallback?.()}
			{:then gltf}
				<T.Mesh geometry={gltf.nodes.Cube.geometry} material={gltf.materials.Material} position={[0, 1, 2,]} />

			{:catch err}
        {@render error?.({ error: err })}
			{/await}

      {@render children?.({ ref })}
		</T.Group>
	